#ifndef _OTA_CERTS_
#define _OTA_CERTS_

#include <pgmspace.h>

// A master cert that allows access to GitHub's different endpoints
static const char OTAGH_CA_CERT[] PROGMEM =
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIEoDCCBEagAwIBAgIQKhb1wgEYB/cKkmPdPDmp8jAKBggqhkjOPQQDAjCBjzEL\r\n"
    "MAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE\r\n"
    "BxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5T\r\n"
    "ZWN0aWdvIEVDQyBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMB4X\r\n"
    "DTI1MDIwNTAwMDAwMFoXDTI2MDIwNTIzNTk1OVowFzEVMBMGA1UEAwwMKi5naXRo\r\n"
    "dWIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElbQ+DErBU9/BYlYXV5qx\r\n"
    "aS5Nu5Ucd+scwICjYp7Z2YcJ2Jgu7HBjM1R6+b2d8yZYJlpLB2aX3qGwc1ZscE7w\r\n"
    "HKOCAvkwggL1MB8GA1UdIwQYMBaAFPaFCjsRhuEEfQ6qCyzS7sxke3uuMB0GA1Ud\r\n"
    "DgQWBBSY8zci2pdh0RUe+FTOokexsSdvADAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0T\r\n"
    "AQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwSQYDVR0gBEIw\r\n"
    "QDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUFBwIBFhdodHRwczovL3NlY3RpZ28u\r\n"
    "Y29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUFBwEBBHgwdjBPBggrBgEFBQcwAoZD\r\n"
    "aHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdvRUNDRG9tYWluVmFsaWRhdGlv\r\n"
    "blNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL29jc3Auc2Vj\r\n"
    "dGlnby5jb20wggF9BgorBgEEAdZ5AgQCBIIBbQSCAWkBZwB1AJaXZL9VWJet90OH\r\n"
    "aDcIQnfp8DrV9qTzNm5GpD8PyqnGAAABlNNtegoAAAQDAEYwRAIgARjCCRJjeSsj\r\n"
    "1aDf1k2e9k7BMQOzBk5NH2yNZnExXJYCIEx3XBFFZ4kmjLneOJG0C/W/K+1W+Lx5\r\n"
    "vY+UM1oFAV7SAHYAGYbUxyiqb/66A294Kk0BkarOLXIxD67OXXBBLSVMx9QAAAGU\r\n"
    "0215mgAABAMARzBFAiA9Ui4Z4WE8Mg11ZmjscGtczwGRFgRySEgdY3O/Hmn3rgIh\r\n"
    "AJSNm0C0lHX7yf3IW+dMIctrApWm2rL2P6Wei1wEBuovAHYAyzj3FYl8hKFEX1vB\r\n"
    "3fvJbvKaWc1HCmkFhbDLFMMUWOcAAAGU0215zwAABAMARzBFAiBNfjmh0gVRA7aq\r\n"
    "sfUsyIvg9rvkxJjrV0/w4sjsTbVqngIhAM8fdljMks2Hh+It5rYLMS4utsRzTDEU\r\n"
    "8zBOHS3K9bSDMCMGA1UdEQQcMBqCDCouZ2l0aHViLmNvbYIKZ2l0aHViLmNvbTAK\r\n"
    "BggqhkjOPQQDAgNIADBFAiAHU6XJYeE/cjpdM9Rfn0IdGZEEs0zTAuyN0mUkXnZa\r\n"
    "KQIhAPkzw1jn3t/HCIVT98ZYrTYNsxElJRY6JH89pJlVt3Ay\r\n"
    "-----END CERTIFICATE-----\r\n";

#endif